<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	<PropertyGroup>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
	</PropertyGroup>

	<PropertyGroup>
		<GitExtensionsDownloadPath Condition="$(GitExtensionsDownloadPath) == ''">..\..\gitextensions.shared</GitExtensionsDownloadPath>
		<!-- path is relative to $(ProjectDir) -->
	</PropertyGroup>

	<PropertyGroup>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Resources\IconJira.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Atlassian.SDK" Version="13.0.0" />
		<PackageReference Include="NString" Version="2.1.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="System.ComponentModel.Composition" Version="6.0.0" />
		<PackageReference Include="Microsoft.VisualStudio.Threading" Version="17.13.61" />
	</ItemGroup>

	<!-- Reference to GitExtensions host dlls -->
	<ItemGroup>
		<Reference Include="GitUIPluginInterfaces">
			<HintPath>C:\Program Files\GitExtensions\GitUIPluginInterfaces.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="ResourceManager">
			<HintPath>C:\Program Files\GitExtensions\ResourceManager.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="GitExtUtils">
			<HintPath>C:\Program Files\GitExtensions\GitExtUtils.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="GitCommands">
			<HintPath>C:\Program Files\GitExtensions\GitCommands.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="GitExtensions.Extensibility">
			<HintPath>C:\Program Files\GitExtensions\GitExtensions.Extensibility.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="GitUI">
			<HintPath>C:\Program Files\GitExtensions\GitUI.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>
	<ItemGroup>
	  <Compile Update="Properties\Resources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Resources.resx</DependentUpon>
	  </Compile>
	</ItemGroup>
	<ItemGroup>
	  <EmbeddedResource Update="Properties\Resources.resx">
	    <CustomToolNamespace>Resources</CustomToolNamespace>
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>Resources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>


	<!-- Pack as .nupkg with dependency on GitExtensions.Extensibility -->
	<PropertyGroup>
		<NuspecFile>$(MSBuildThisFileDirectory)$(MSBuildProjectName).nuspec</NuspecFile>
		<Authors>IErof</Authors>
		<PackageVersion>1.1.0</PackageVersion>
		<Company>freelance</Company>
		<Description>A plugin for Git Extensions to add commit comment from your Jira.</Description>
		<PackageProjectUrl>https://github.com/ierof/gitextensions.jiracommithintplugin</PackageProjectUrl>
		<PackageTags>GitExtensions</PackageTags>
	</PropertyGroup>
	<Target Name="SetPackageProperties" BeforeTargets="GenerateNuspec">
		<PropertyGroup>
			<NuspecProperties>
				id=$(PackageId);
				version=$(PackageVersion);
				configuration=$(Configuration);
				tags=$(PackageTags.Replace(';',' '));
				projectUrl=$(PackageProjectUrl);
				iconUrl=$(PackageIconUrl);
				repositoryUrl=$(RepositoryUrl);
				repositoryType=$(RepositoryType);
				repositoryCommit=$(RepositoryCommit);
				author=$(Authors);
				copyright=$(Copyright);
				description=$(Description);
				targetDir=$(TargetDir);
			</NuspecProperties>
		</PropertyGroup>
	</Target>

</Project>
